/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.Date;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vta_pasaje_grupo7.AccesoDato.*;
import vta_pasaje_grupo7.Entidades.*;

/**
 *
 * @author ST-P
 */
public class GestionPasajes extends javax.swing.JInternalFrame {

   DefaultTableModel modelo=new DefaultTableModel();
    DefaultTableModel modelo2=new DefaultTableModel();
    public GestionPasajes() {
        initComponents();
        llenarComboPasajeros();
         llenarComboRutas();
         armarCabecera();
       
         PasajeData pd=new PasajeData();
         cargarColectivos();
//         try{
//         if(pd.pasajesVendidos().isEmpty()){
//             cargarColectivos();
//         
//    }else{
//            
//         ColectivoData cd=new ColectivoData();
//        
//         
//             for(Colectivo c:cd.listarColectivos()){
//                 for(Pasaje p:pd.pasajesVendidos()){
//               if(p.getColectivo().getIdColectivo()==c.getIdColectivo()){
//                   
//        Colectivo colectivo=pd.obtenerColectivoPorPasaje(p);
//         
//       jcColectivos.addItem(colectivo);
//         
//             }
//                 }
//         }
//            
//         
//    }
//         }catch(Exception e){
//             System.out.println(e.getMessage());
//         }
         armarCabeceraHistorialPasajes();
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcHorarios = new javax.swing.JComboBox<>();
        jcRutas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcPasajeros = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jdFecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAsientos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jcColectivos = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jlPrecio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtHistorialPasajes = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("Gestión pasajes");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Gestionar pasajes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Elija una ruta");

        jcHorarios.setEnabled(false);

        jcRutas.setEnabled(false);
        jcRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcRutasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Elija un horario");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Elija un pasajero");

        jcPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcPasajerosActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha: ");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Emitir pasaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Asiento");

        jtAsientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtAsientos.setEnabled(false);
        jtAsientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtAsientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtAsientos);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Colectivos disponibles:");

        jcColectivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcColectivosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Precio del pasaje");

        jlPrecio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("$");

        jtHistorialPasajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtHistorialPasajes.setEnabled(false);
        jScrollPane2.setViewportView(jtHistorialPasajes);

        jLabel10.setText("Historial de pasajes por ruta");

        jButton2.setText("Anular venta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addGap(399, 399, 399)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jcPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(jcRutas, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcColectivos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel6)))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(406, 406, 406)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(169, 169, 169))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(417, 417, 417))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcRutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jdFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jcColectivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel9))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcPasajerosActionPerformed
        jcRutas.setEnabled(true);
       
    }//GEN-LAST:event_jcPasajerosActionPerformed

    private void jcRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcRutasActionPerformed
        ColectivoData cd=new ColectivoData();
    PasajeData pd=new PasajeData();
     
        for(Colectivo c:cd.listarColectivos()){
          
          
     }
        jcHorarios.removeAllItems();
        jcHorarios.setEnabled(true);
        HorarioData hd=new HorarioData();
        
Ruta ruta=(Ruta) jcRutas.getSelectedItem();
       
       
if(ruta.getOrigen().toLowerCase().equals("san luis") && ruta.getDestino().toLowerCase().equals("villa mercedes")){
jlPrecio.setText("15000");
}else if(ruta.getOrigen().toLowerCase().equals("san luis")&& ruta.getDestino().toLowerCase().equals("buenos aires")){
jlPrecio.setText("30000");
}else if(ruta.getOrigen().toLowerCase().equals("san luis")&& ruta.getDestino().toLowerCase().equals("villa de la quebrada")){
jlPrecio.setText("8000");
}else if(ruta.getOrigen().toLowerCase().equals("san luis")&& ruta.getDestino().toLowerCase().equals("merlo")){
jlPrecio.setText("20000");
}
for(Horario h:hd.horarioDisponiblesPorRuta(ruta)){
    
jcHorarios.addItem(h);
}

for(Pasaje p:pd.pasajesVendidosPorRuta(ruta.getIdRuta())){
 borrarFilasHistorial();
   if(ruta.getIdRuta()==p.getRuta().getIdRuta()){
    
modelo2.addRow(new Object[]{p.getPasajero(),p.getColectivo(),p.getRuta(),p.getFechaViaje(),
  p.getHoraViaje(),
  p.getAsiento(),
  p.getPrecio()});
   }
    System.out.println(pd.obtenerColectivoPorRuta(ruta.getIdRuta()));
//  for(Colectivo c:pd.obtenerColectivoPorRuta(ruta.getIdRuta())){
//      System.out.println(c);
//  jcColectivos.addItem(c);
//  }
}

    }//GEN-LAST:event_jcRutasActionPerformed

    private void jtAsientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtAsientosMouseClicked
        // Obtener la fila y columna donde se hizo clic
                int fila = jtAsientos.rowAtPoint(evt.getPoint());
                int columna = jtAsientos.columnAtPoint(evt.getPoint());
          

                int valor=(int) modelo.getValueAt(fila, columna);
                JOptionPane.showMessageDialog(this, "El asiento elegido es: "+valor);
                AsientoSeleccionado.setAsiento(valor);
    }//GEN-LAST:event_jtAsientosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PasajeData pd=new PasajeData();
        Pasajero pasajero=(Pasajero) jcPasajeros.getSelectedItem();
        Ruta ruta=(Ruta) jcRutas.getSelectedItem();
                Horario horario=(Horario) jcHorarios.getSelectedItem();
                LocalTime horasalida=horario.getHoraSalida();
                java.util.Date fecha= jdFecha.getDate();
                Instant instant = fecha.toInstant();
LocalDate localDate = instant.atZone(ZoneId.systemDefault()).toLocalDate();
                Colectivo colectivo=(Colectivo) jcColectivos.getSelectedItem();
               int asiento=AsientoSeleccionado.getAsiento();
               double precio=Double.parseDouble(jlPrecio.getText());
               Pasaje pasaje=new Pasaje(pasajero,colectivo,ruta,localDate,horasalida,asiento,precio);
              pd.venderPasaje(pasaje);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcColectivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcColectivosActionPerformed
       borrarFilas();
        ColectivoData cd=new ColectivoData();

    
Colectivo colectivo=(Colectivo) jcColectivos.getSelectedItem();
int capacidad =colectivo.getCapacidad();
        System.out.println(capacidad);
int fila1=capacidad/4;
int fila2=fila1+fila1;
int fila3=fila2+fila1;
int fila4=fila3+fila1;
for(int i=0;i<fila1;i++){
modelo.addRow(new Object[]{i+1,fila1+i,fila2+i,fila3+i});
}
    }//GEN-LAST:event_jcColectivosActionPerformed
public void llenarComboPasajeros(){
PasajeroData pd=new PasajeroData();
for(Pasajero p:pd.listaDePasajeros()){
    jcPasajeros.addItem(p);
}
}
public void llenarComboRutas(){
RutaData rd=new RutaData();
for(Ruta r:rd.rutasDisponibles()){
jcRutas.addItem(r);
}
}
public void borrarFilas(){
while(modelo.getRowCount()>0){
modelo.removeRow(0);
}
}
public void armarCabecera(){
modelo.addColumn("Fila A");
modelo.addColumn("Fila B");
modelo.addColumn("Fila C");
modelo.addColumn("Fila D");
jtAsientos.setModel(modelo);
}

public void cargarColectivos(){
ColectivoData cd=new ColectivoData();
for(Colectivo c:cd.listarColectivos()){
jcColectivos.addItem(c);
}
}
public void armarCabeceraHistorialPasajes(){
modelo2.addColumn("Pasajero");
modelo2.addColumn("Colectivo");
modelo2.addColumn("Ruta");
modelo2.addColumn("Fecha de viaje");
modelo2.addColumn("Hora de viaje");
modelo2.addColumn("Asiento");
modelo2.addColumn("Precio");
jtHistorialPasajes.setModel(modelo2);
}
//public void rellenarHistorialPasajes(){
//    PasajeData pd=new PasajeData();
//for(Pasaje p:pd.pasajesVendidos() ){
//  modelo2.addRow(new Object[]{p.getPasajero(),p.getColectivo(),p.getRuta(),p.getFechaViaje(),
//  p.getHoraViaje(),
//  p.getAsiento(),
//  p.getPrecio()
//  
//  });
//}
//}
public void borrarFilasHistorial(){
while(modelo2.getRowCount()>0){
modelo2.removeRow(0);
}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<Colectivo> jcColectivos;
    private javax.swing.JComboBox<Horario> jcHorarios;
    private javax.swing.JComboBox<Pasajero> jcPasajeros;
    private javax.swing.JComboBox<Ruta> jcRutas;
    private com.toedter.calendar.JDateChooser jdFecha;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JTable jtAsientos;
    private javax.swing.JTable jtHistorialPasajes;
    // End of variables declaration//GEN-END:variables
}
